config/routes.rb
Rails.application.routes.draw do

  resources :reviews do
    resources :comments
  end

  root "reviews#index"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :review

  validates :body, presence: true
end

app/models/review.rb
class Review < ApplicationRecord


  # Add an association that has a 1-to-many relationship
  has_many :comments

  geocoded_by :address
  after_validation :geocode

  validates :title, presence: true
  validates :body, length: {minimum: 10}
  validates :score, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 10 }
  validates :restaurant, presence: true
  validates :address, presence: true

  def to_param
    id.to_s + "-" + title.parameterize
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create

    # find review
    @review = Review.find(params[:review_id])

    @comment = @review.comments.new(params.require(:comment).permit(:body))

    @comment.save

    redirect_to review_path(@review)

  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def index
    # This is our list page for our reviews
    @price = params[:price]
    @cuisine = params[:cuisine]
    @location = params[:location]


  #start with all Reviews
  @reviews = Review.all

  # filtering by Price
  if @price.present?
    @reviews = @reviews.where(price: @price)
  end

  # filter by Cuisine
  if @cuisine.present?
    @reviews = @reviews.where(cuisine: @cuisine)
  end

  # search near location
  if @location.present?
    @reviews = @reviews.near(@location)
  end

end


  def new
    # The form for adding a new review
    @review = Review.new
  end


  def create
    # Take info from the form and add it to the model
    @review = Review.new(form_params)

    # Check if model can be saved, if it is, we go back to the home page
    # If it does not, the new form shows

    if @review.save
      redirect_to root_path

    else
      # Show the view for new.html.erb
      render "new"
    end

  end

  def show
    # individual review page
    @review = Review.find(params[:id])

  end

  def destroy

    #find the review
    @review = Review.find(params[:id])

    #destroy
    @review.destroy

    #redirect to the home page
    redirect_to root_path

  end


  def edit

    #find the review (to edit)
    @review = Review.find(params[:id])

  end

  def update
    #find the review
    @review = Review.find(params[:id])

    #update with new information
    if @review.update(form_params)

      #redirect
      redirect_to review_path(@review)
    else
      render "edit"
    end

  end


  def form_params
    params.require(:review).permit(:title, :restaurant, :address, :body, :cuisine, :price, :score, :ambience)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for :page_title %> - Bien Reviews - The Best Reviews of Restaurants In The World</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav>
        <h1>
          <%= link_to root_path do %>
            <% image_tag "bien-logo.svg" %>
          <% end %>
        </h1>
      </nav>

      <nav>
        <%= link_to "Add a review", new_review_path %>
      </nav>

    </header>

  <main>
    <%= yield %>
  </main>

    <footer>
      <p>Copyright Bien 2019</p>
    </footer>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= simple_form_for @review do |f| %>
  <%= f.input :title %>
  <br>
  <%= f.input :restaurant %>
  <br>
  <%= f.input :address %>
  <br>
  <%= f.input :body %>
  <br>
  <%= f.input :cuisine %>
  <br>
  <%= f.input :price %>
  <br>
  <%= f.input :score %>
  <br>
  <%= f.input :ambience %>

<br>

  <%= f.button :submit %>

<% end %>

app/views/reviews/edit.html.erb
<h3>Edit your restaurant review</h3>

<%= render "form" %>

app/views/reviews/index.html.erb
<% content_for :page_title, "Homepage" %>

<nav class="filters">
  <%= active_link_to "All Restaurants", root_path, active: { price: nil, cusine: nil, location: nil } %>

  <div>
    <%= active_link_to "$", root_path(price: 1, cuisine: @cuisine, location: @location), active: { price: 1 } %>
    <%= active_link_to "$$", root_path(price: 2, cuisine: @cuisine, location: @location), active: { price: 2 } %>
    <%= active_link_to "$$$", root_path(price: 3, cuisine: @cuisine, location: @location), active: { price: 3 } %>
  </div>

  <div>
    <%= active_link_to "Indian", root_path(cuisine: "Indian", price: @price, location: @location), active: { cuisine: "Indian" } %>
    <%= active_link_to "Mexican", root_path(cuisine: "Mexican", price: @price, location: @location), active: { cuisine: "Mexican" } %>
    <%= active_link_to "American", root_path(cuisine: "American", price: @price, location: @location), active: { cuisine: "American" } %>
  </div>


  <form action="/">
    <input type="text" name="location"
      placeholder="Search location..." value="<%= @location %>">

      <input type="hidden" name="price" value="<%= @price %>">
      <input type="hidden" name="cuisine" value"<%= @cuisine %>">
  </form>
</nav>





<% @reviews.each do |review| %>
  <div class="review">
    <%= link_to review_path(review) do %>

    <h2><%= review.title %></h2>

    <p> <%= review.cuisine %> -
    <%= pluralize review.comments.count, "comment" %>
    </p>

    <% end %>

  </div>
<% end %>

app/views/reviews/new.html.erb
<% content_for :page_title, "Add a new review" %>

<h3>Add your new restaurant review</h3>

<%= render "form" %>

app/views/reviews/show.html.erb
<% content_for :page_title, @review.title %>

<h1><%= @review.title %> </h1>
<h2><%= @review.restaurant %> </h2>
<h3><%= @review.address %> </h3>

<div class="score">
  <%= @review.score %> / 10
</div>

<% if @review.ambience.present? %>
  <div class="ambience">
    Ambience: <%= @review.ambience %>
  </div>
<% end %>

<div class="price">
  Price: <%= @review.price %>
</div>

<div class="cuisine">
  Cuisine: <%= @review.cuisine %>
</div>


<div class="body">
  <%= simple_format @review.body %>
</div>

<div class="actions">
  <%= link_to "Edit this review", edit_review_path(@review) %>
  <%= link_to "Delete this review", review_path(@review), method: :delete, data: {confirm: "Are you sure?"} %>
</div>


<h3>Comments</h3>

  <% @review.comments.order("created_at desc").each do |comment| %>

    <div class="comment">
      <%= simple_format comment.body %>

      <p class="posted">Posted <%= time_ago_in_words comment.created_at %> ago </p>
    </div>

  <% end %>


<h3>Add a comment</h3>
  <%= simple_form_for [@review, Comment.new] do |f| %>
  <%= f.input :body %>
  <%= f.button :submit, "Add Comment" %>
<% end %>